app/urls.py
from django.urls import path
from app import views

app_name = 'poll'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login', views.admin_login, name='login'),
    path('create_poll/', views.create_poll, name='create_poll'),
    path('show_polls/', views.show_poll, name='show_polls'),
    path('show_polls/<slug:username>/', views.show_polls, name='show_polls'),
    path('save_poll/', views.save_poll, name='save_poll'),
    path('polling/<uuid:id>/', views.polling, name='polling'),
    path('logout/', views.admin_logout, name='logout'),
    path('poll_result/<uuid:id>/', views.poll_result, name='poll_result'),
    path('get_data/<uuid:id>/', views.get_data, name='get_data'),
]

live_poll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.

class Otp(models.Model):
	email = models.CharField(max_length=100)
	otp = models.CharField(max_length=6)

class Poll(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	question = models.CharField(max_length=100)

	def __str__(self):
		return self.question

class PollOptions(models.Model):
	question = models.ForeignKey(Poll, related_name='poll_option', on_delete=models.CASCADE)
	option = models.CharField(max_length=100)
	value = models.IntegerField(default=0)

	def __str__(self):
		return self.question.question

app/forms.py
from django import forms
from app.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ("first_name","last_name", "username", 
			"email", "password1", "password2", 
		)


class OtpForm(forms.ModelForm):
	class Meta:
		models = Otp 
		fields = ('email', 'otp')


class PollForm(forms.ModelForm):
	class Meta:
		models = Poll
		fields = ["__all__"]


class PollOptionForm(forms.ModelForm):
	class Meta:
		models = PollOptions
		fields = ["__all__"]

app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from .models import Poll, PollOptions
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
from .serializers import PollSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response 
from django.conf import settings
from app.forms import UserForm
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.


def home(request, *args, **kwargs):
	return render(request, 'index.html')



def create_poll(request, *args, **kwargs):
	if request.user.is_authenticated:
		return render(request, 'create_poll.html')
	return render(request, 'login.html')


@csrf_exempt
def save_poll(request, *args, **kwargs):
	question = request.POST.get('question')
	options = request.POST.get('options')
	options_arr = []
	for i in range(int(options)):
		options_arr.append(request.POST.get("option" + str(i+1)))

	if question:
		poll = Poll(user=request.user, question=question)
		poll.save()

	for i in options_arr:
		if i != None:
			poll_options = PollOptions(question=poll, option=i)
			poll_options.save()

	return redirect(reverse('poll:create_poll'))

def show_polls(request, username, *args, **kwargs):
	if(not User.objects.all().filter(username=username)):
		return render(request, 'search_poll.html', {'message': 'Invalid User'})
	id = User.objects.get(username=username).id
	contact_list = Poll.objects.all().filter(user=id)
	paginator = Paginator(contact_list, 20)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request, 'all_polls.html', {'page_obj': page_obj, 'cs':settings.REAL_SITE})


def show_poll(request, *args, **kwargs):
	if(not request.user.is_authenticated):
		return render(request, "search_poll.html")
	id = User.objects.get(username=request.user).id
	contact_list = Poll.objects.all().filter(user=id)
	paginator = Paginator(contact_list, 20)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request, 'all_polls.html', {'page_obj': page_obj, 'cs':settings.REAL_SITE})


@csrf_exempt
@api_view(['GET', 'POST'])
def get_data(request, id, *args, **kwargs):
	if request.method == 'POST':
		id = id
		serializer = PollSerializer(Poll.objects.all().get(id=id))
		return Response(serializer.data)
	return JsonResponse({'msg': 'Invalid URL'})	


def poll_result(request, id, *args, **kwargs):
	return render(request, 'poll_result.html', {'id':id})


@csrf_exempt
def register(request):
	"""
	REGISTRATION PAGE FOR PATIENTS
	"""
	if request.user.is_authenticated:
		return redirect("poll:home")
	form = UserForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		form.save()
		return redirect("poll:login")
	return render(request, "register.html", {"form": form, "errors": form.errors.as_json() })


@csrf_exempt
def admin_login(request, *args, **kwargs):
	if request.user.is_authenticated:
		return redirect("poll:home")
	username = request.POST.get('username')
	password = request.POST.get('password')
	user = authenticate(request, username=username, password=password)
	print(user)
	if user:
		login(request, user)
		return redirect(reverse('poll:create_poll'))
	return render(request, 'login.html')


@csrf_exempt
def polling(request, id, *args, **kwargs):
	if request.method == 'POST':
		uid = request.POST.get('id')
		if uid:
			poll_option = PollOptions.objects.all().filter(id=uid).first()
			poll_option.value = poll_option.value + 1
			poll_option.save()
			return redirect('poll:poll_result', id=id)
	return render(request, 'polling.html', {'id':id})

@csrf_exempt
def admin_logout(request, *args, **kwargs):
	if request.POST.get('logout') == 'ok':
		logout(request)
	return render(request, 'login.html')

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Let's poll</title>
	<link rel="icon" href="https://github.com/jhabarsingh/polling_app/blob/master/live_poll/app/static/img/survey.png?raw=true" type="image/png" sizes="16x16">
	<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
	{% block content %}
	{% endblock %}

	<script>
		function getCookie(name) {
		    let cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        const cookies = document.cookie.split(';');
		        for (let i = 0; i < cookies.length; i++) {
		            const cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		const csrftoken = getCookie('csrftoken');

		if (document.querySelector(".create_poll_button")){
			document.querySelector(".create_poll_button").addEventListener("click", function(){
				window.open("{% url 'poll:create_poll' %}", '_self')
			})
		}

		if (document.querySelector(".home_button")){
			document.querySelector(".home_button").addEventListener("click", function(){
				window.open("{% url 'poll:home' %}", '_self')
			})
		}

		if (document.querySelector(".home_button1")){
			document.querySelector(".home_button1").addEventListener("click", function(){
				window.open("{% url 'poll:register' %}", '_self')
			})
		}

		if (document.querySelector(".all_poll_button")){
			document.querySelector(".all_poll_button").addEventListener("click", function(){
				window.open("{% url 'poll:show_polls' %}", '_self')
			})
		}


		if (document.querySelector(".form_button")) {
			document.querySelector(".form_button").addEventListener("click", function() {
				
				let form = document.createElement('form')
				form.setAttribute('action', "{% url 'poll:login' %}")
				form.setAttribute('method', 'POST')

				let input = document.createElement('input')
				input.setAttribute('name', 'csrfmiddlewaretoken')
				input.setAttribute('type', 'hidden')
				input.value = csrftoken
				form.appendChild(input)

				input = document.createElement('input')
				input.setAttribute('name', 'username')
				input.setAttribute('type', 'text')
				input.value = document.querySelector('.username').value
				form.appendChild(input)

				input = document.createElement('input')
				input.setAttribute('name', 'password')
				input.setAttribute('type', 'password')
				input.value = document.querySelector('.password').value
				form.appendChild(input)

				input = document.createElement('input')
				input.setAttribute('name', 'submit')
				input.setAttribute('type', 'submit')
				input.value = 'submit'
				form.appendChild(input)
				form.style.visibility = 'hidden';
				document.querySelector('body').appendChild(form)
				input.click();
			})			

		}
	</script>
</body>
</html>

app/templates/create_poll.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Let's poll</title>
    <link rel="icon" href="{% static 'img/survey.png' %}" type="image/png" sizes="16x16">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap');
      
      .main {
      	overflow: hidden;
      	display: flex;
      	height: 100vh;
      }

      .main > div {
      	position: absolute;
      	top:0px;
      	left:0px;
      	height: 100vh;
      	overflow: scroll;
      }

     .question {
        background: lightgreen;
        min-height: 100vh;
        width: 100%;
        z-index: 1;
      }

      .question > p:nth-child(1) {
      	font-family: 'Gamja Flower', cursive;
      	text-align: center;
      	padding-top: 10px;
      	padding-bottom: 10px;
      	font-size: 50px;
      }

      .sec-p {
      	font-family: 'Gamja Flower', cursive;
      	text-align: center;
      	padding-top: 10px;
      	padding-bottom: 0px;
      	font-size: 25px;
      	display: inline-block;
      }

      div > div {
      	text-align: center;
      }
      .sec-p + input {
      	width: 70px;
      	margin-left: 10px;
      	font-weight: bolder;
      }


      .question > textarea {
      	width: 90%;
      	margin-left:5%;
      	min-height:40vh;
      	border:1px solid lightgreen;
      	outline: none;
      	font-size: 25px;
      	font-family: ubuntu;
      	font-weight: bold;
      	background: linear-gradient(45deg, white, #fff);
      	font-style: italic;
      }

      .poll-option	 {
        background: lightgreen;
        min-height: 100vh;
        width: 100%;
        z-index: 0;
      	height: 100vh;
      	overflow: scroll;
      }

      .poll-option > p:nth-child(1) {
      	font-family: 'Gamja Flower', cursive;
      	text-align: center;
      	padding-top: 10px;
      	padding-bottom: 10px;
      	font-size: 40px;
      }

      .lg {
      	position: absolute;
      	width: 100px;
      	min-height: 100px;
      	bottom: 0px;
      	right: 0px;
      	z-index: 3;
      	overflow: hidden;
      }
      .logout-circle {
      	width: 200px;
      	height: 200px;
      	background: violet;
      	position: absolute;
      	bottom: -100px;
      	right:-100px;
      	z-index: 3;
      	border-radius: 50%;
      	transition: 300ms linear;
      	cursor: pointer;
      }

      .logout-circle:hover {
      	background: blue;
      	transition: 300ms linear;
      }

      i {
      	position: relative;
      	bottom: -70px;
      	right: 15px;
      	width: 100px;
      }

      .alla {
      	animation: 400ms up-down linear forwards; 
      	position: absolute;
      	padding: 20px;

      }

      .alla:hover {
      	transform: translateY(-1px);
      }
      @keyframes up-down {
      	from {
      		top: -500px;
      	}
      	to {
      		top: 20vh;
      	}
      }

    </style>
  </head>
  <body>
  	<div class='lg'>
  		<div class='logout-circle'>
  			  <i class="large material-icons">lock_outline</i>
  		</div>
  	</div>
  	<div class='main'>
  		<div class='question'>
	      	<p>Type The Question ?</p> 
	      	<textarea></textarea>
	      	<div>
	      		<p class='sec-p'>No Of Options It Has</p>
	      		<input type="number" class='values'>
	      	</div>
	      	<button class='btn btn-danger d-block mx-auto w-25 mt-4 question-next' >Next</button>
	    </div>

	    <div class='poll-option pb-3'>
	      	<p>Type The Poll Options</p>
	      	<div class="polls">
	      		
	      	</div>
	      	<button class='btn btn-warning mx-auto w-25 mt-4 question-next reset-question' >Reset</button>
	      	<button class='btn btn-danger  mx-auto w-25 mt-4 question-next submit-question' >Submit</button>
	    </div>

  	</div>
  </body>

  <script>

  	function insertPoll() {
  		polls = document.querySelector('.poll-option > .polls')
  		let len = polls.children.length;

    	if (len != localStorage.getItem('options') && localStorage.getItem('options')) {
	  		polls.innerHTML= "";
	    	let val = localStorage.getItem('options');
	    	for(let i=0; i< val; i++) {
		    	let poll = document.createElement('input')
		    	poll.setAttribute('placeholder', i + 1 + ' Poll Option')
		    	poll.setAttribute('placeholder', i + 1 + ' Poll Option')
		    	poll.style.textAlign = 'center';
		    	poll.style.width = '90%';
		    	poll.style.marginBottom = '20px';
		    	poll.style.outline = 'none';
		    	poll.style.height = '80px'; 
		    	poll.style.border = '1px solid lightgreen';
		    	poll.style.fontFamily = 'ubuntu';
		    	poll.style.fontWeight = 'bolder';
		    	poll.style.fontStyle = 'italic';
		    	polls.style.fontSize = '20px';
		    	polls.appendChild(poll);
		    }	
	    }
	    add_listener();
  	}

  	if (localStorage.getItem('question')) {
  		document.querySelector('textarea').value = localStorage.getItem('question');
  	}
  	if (localStorage.getItem('options')) {
  		document.querySelector('.values').value = localStorage.getItem('options');
  		for(let i=0; i<localStorage.getItem('options'); i++) {
  			if (localStorage.getItem("option"+ (i+1))) {
  				insertPoll();
  				document.querySelector('.poll-option > .polls').children[i].value = localStorage.getItem("option"+ (i+1));
  			}
  		}
  	}

  	let ques = document.querySelector('.question'); 
  	let opt = document.querySelector('.poll-option');
    document.querySelector('.question-next').addEventListener("click", function() {
    	localStorage.setItem('question', document.querySelector('textarea').value);
    	localStorage.setItem('options', document.querySelector('.values').value);
    	if (+localStorage.getItem('options') <=0 || localStorage.getItem('options') == '' || localStorage.getItem('question') == '') {
    		alert('details need to be filled and option should be greater than 0');
    	}
    	else {
    		ques.style.zIndex = 0;
	    	opt.style.zIndex = 1;
	    	localStorage.setItem('current', '2');
	    	insertPoll();
    	}
    })

    insertPoll();
    
    if (localStorage.getItem('current') == 2) {
  		ques.style.zIndex = 0;
    	opt.style.zIndex = 1;
  	}

    document.querySelector('.reset-question').addEventListener("click", function() {
    	ques.style.zIndex = 1;
    	opt.style.zIndex = 0;
    	localStorage.clear();
    	document.querySelector('.poll-option > .polls').innerHTML = '';
    	document.querySelector('textarea').value = '';
    	document.querySelector('.values').value = '';
    	localStorage.setItem('current', '1');
    })


    function add_listener() {
    	console.log(Object.entries(document.querySelector('.poll-option > .polls').children).length);
	    if (Object.entries(document.querySelector('.poll-option > .polls').children).length) {
	    	Object.entries(document.querySelector('.poll-option > .polls').children).map((element, index) => {
	    		element[1].addEventListener("change", () => {
	    			localStorage.setItem('option' + (index + 1), element[1].value);
	    		})
	    	})
	    }
    }

// CSRF PART

   function getCookie(name) {
		    let cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        const cookies = document.cookie.split(';');
		        for (let i = 0; i < cookies.length; i++) {
		            const cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		const csrftoken = getCookie('csrftoken');



    document.querySelector('.submit-question').addEventListener("click", function() {
    	let options = [];
    	for(let i=0; i<localStorage.getItem('options'); i++) {
    		options.push(localStorage.getItem('option' + (i+1)));
    	}
    	console.log(options);

    	let form = document.createElement('form')
		form.setAttribute('action', "{% url 'poll:save_poll' %}")
		form.setAttribute('method', 'POST')

		let input = document.createElement('input')
		input.setAttribute('name', 'csrfmiddlewaretoken')
		input.setAttribute('type', 'hidden')
		input.value = csrftoken
		form.appendChild(input)

		input = document.createElement('input')
		input.setAttribute('name', 'question')
		input.setAttribute('type', 'text')
		input.value = localStorage.getItem('question')
		form.appendChild(input)

		input = document.createElement('input')
		input.setAttribute('name', 'options')
		input.setAttribute('type', 'number')
		input.value = localStorage.getItem('options')
		form.appendChild(input)

		for(let i=0; i<options.length; i++) {
			input = document.createElement('input')
			input.setAttribute('name', 'option'+(i+1))
			input.setAttribute('type', 'text')
			input.value = options[i]
			form.appendChild(input)			
		}


		input = document.createElement('input')
		input.setAttribute('name', 'submit')
		input.setAttribute('type', 'submit')
		input.value = 'submit'
		form.appendChild(input)
		form.style.visibility = 'hidden';
		document.querySelector('body').appendChild(form)
		input.click();
		alert('poll is saved in the database ')
    })


    document.querySelector('.logout-circle').addEventListener("click", () => {
    	let a = "<p style='text-align:center;font-family:ubuntu;font-size:20px;font-weight:bolder;'>Are You Sure You Want To Logout 	</p><div><button class='btn btn-primary mr-4 canceller '>Cancel</button><button class='btn btn-danger logouter'>Logout</button></div>"
    	let modal = document.createElement('div');
    	let blur = document.createElement('blur');
    	blur.style.position = 'absolute'
    	blur.style.width = '100vw';
    	blur.style.height = '100vh';
    	blur.style.background = 'rgba(0, 0, 0, .8)'
    	blur.style.zIndex = 5;
    	blur.style.top = '0px';
    	modal.style.width = "70%";
    	modal.classList.add('alla');
    	modal.style.background = "silver";
    	modal.style.marginLeft = '15%'
    	modal.style.boxShadow = '0 0 50px rgba(0, 0, 0, .1)'
    	modal.style.position = 'absolute';
    	modal.style.zIndex = 6;
    	modal.style.top= '20vh';
    	modal.style.minHeight = '200px';
    	modal.style.borderRadius = '10px';
    	modal.innerHTML = a;
    	document.querySelector('body').appendChild(blur)
    	document.querySelector('body').appendChild(modal)


    	document.querySelector('.canceller ').addEventListener('click', () => {
    		document.querySelector('body').removeChild(modal)
    		document.querySelector('body').removeChild(blur)
    	})

    	document.querySelector('.logouter ').addEventListener('click', () => {
    		let form = document.createElement('form')
			form.setAttribute('action', "{% url 'poll:logout' %}")
			form.setAttribute('method', 'POST')

			let input = document.createElement('input')
			input.setAttribute('name', 'csrfmiddlewaretoken')
			input.setAttribute('type', 'hidden')
			input.value = csrftoken
			form.appendChild(input)

			input = document.createElement('input')
			input.setAttribute('name', 'logout')
			input.setAttribute('type', 'text')
			input.value = 'ok'
			form.appendChild(input)

			input = document.createElement('input')
			input.setAttribute('name', 'submit')
			input.setAttribute('type', 'submit')
			input.value = 'submit'
			form.appendChild(input)
			form.style.visibility = 'hidden';
			document.querySelector('body').appendChild(form)
			input.click();
    	})
    })

  </script>
</html>

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="text-gray-500 bg-gray-900 body-font" style='height:100vh;'>
<section class="text-gray-500 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
      <h1 class="title-font font-medium text-3xl text-white">Login If You Have An Account</h1>
      <p class="leading-relaxed mt-4">Only Registered Users have the permissions to create polls so if you don't have an account click on the register button.</p>
      <button class="text-white bg-purple-400 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg home_button1" style='margin-top:10px;'>Register</button>
      <button class="inline mx-auto mt-5 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg home_button">Home</button>
    </div>
    <div class="lg:w-2/6 md:w-1/2 bg-gray-800 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-white text-lg font-medium title-font mb-5">Sign In</h2>
      <input class="bg-gray-900 rounded border text-white border-gray-900 focus:outline-none focus:border-purple-500 text-base px-4 py-2 mb-4 username" name='username' placeholder="Username" type="text">
      <input class="bg-gray-900 rounded border text-white border-gray-900 focus:outline-none focus:border-purple-500 text-base px-4 py-2 mb-4 password" name='password' placeholder="Password" type="password">
      <button class="text-white bg-purple-500 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg form_button">Login</button>
      <p class="text-xs text-gray-600 mt-3">Your credentials are safe so just chill.</p>
    </div>
  </div>
</section>
</div>
{% endblock %}

app/templates/polling.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Let's poll</title>
    <link rel="icon" href="{% static 'img/survey.png' %}" type="image/png" sizes="16x16">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap');
      #main {
        background: lightgreen;
        min-height:100vh;
        color: balck;
        font-family: 'Gamja Flower', cursive;
      }

      form {
        padding: 30px;
        margin: auto;
        transform: scale(.8);
        box-shadow: 0 0 40px rgba(0, 0, 0, .3);
        border-radius: 20px;
      }

      .question {
        font-size: 30px;
        font-weight: bold;
        margin: auto;
        padding-top: 10px;
        margin-bottom: 20px;
        animation : 10s linear alibaba infinite;
      }

      @keyframes alibaba {
        0%, 50%, 100% {

        }
        25% {
          transform: rotate(1deg);
        }
        75% {
          transform: rotate(-1deg);
        }
      }
      label{
          font-size: 25px;
          margin-left: 10px;

      }

      .let {
        font-size: 40px;
        font-weight: bold;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <!-- 38cd1199-25eb-4823-b3a6-1abc029d7221 -->
      <div id="main">
        <p class='let'> Let's Poll</p>
        <form>
          <div class='text-align-center'>
              <div class='question text-align-center'></div>
              <div class='option'>
               
              </div>
          </div>
        <button type="submit" class="btn btn-primary submit">Submit</button>
      </form>        
      </div>

    <script>
      if(localStorage.getItem('{{id}}') == 'true') {
          window.open( "{% url 'poll:poll_result' id=id  %}", '_self')
      }
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');  


      let ques ;
      let lab = [];
      let link = "{% url 'poll:get_data' id=id %}"
      fetch(link, {
        method: "POST",
        credentials: "same-origin",
        headers: {
            "X-CSRFToken": getCookie("csrftoken"),
            "Accept": "application/json",
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
          id: '{{id}}'
        })
      }).then((res) => {
        return res.json()
      }).then((res) => {
        ques = res.question
        res = res.poll_option
        let html;
        let labels;
        document.querySelector('.question').innerText = ques;
         for(let i=0; i<res.length; i++) {
            labels = document.createElement('label')
            labels.setAttribute('key', i+1)
            labels.innerText = res[i].option
            let html = document.createElement('div')
            html.classList.add('form-check')
            input = document.createElement('input')
            input.classList.add('form-check-input',  'position-static')
            input.type = 'radio'
            input.name = 'option'
            input.id = res[i].id;
            input.value = res[i].option

            html.appendChild(input)
            html.appendChild(labels)

            document.querySelector('.option').appendChild(html)
         }
          
        
      }).catch(() => {

      })


      document.querySelector('.submit').addEventListener('click', (event) => {
        event.preventDefault();
          let sol;
          Object.entries(document.querySelectorAll('[type="radio"]')).map((el) => {
            if (el[1].checked) {
              sol = el[1].getAttribute('id')
            }
          })
          if (sol) {
            localStorage.setItem('{{id}}', 'true');
              let form = document.createElement('form')
              form.setAttribute('action', "{% url 'poll:polling' id=id %}")
              form.setAttribute('method', 'POST')

              let input = document.createElement('input')
              input.setAttribute('name', 'csrfmiddlewaretoken')
              input.setAttribute('type', 'hidden')
              input.value = csrftoken
              form.appendChild(input)

              input = document.createElement('input')
              input.setAttribute('name', 'id')
              input.setAttribute('type', 'number')
              input.value = +sol
              form.appendChild(input)

              input = document.createElement('input')
              input.setAttribute('name', 'submit')
              input.setAttribute('type', 'submit')
              input.value = 'submit'
              form.appendChild(input)
              form.style.visibility = 'hidden';
              document.querySelector('body').appendChild(form)
              input.click();
              console.log(sol)
              alert('Thank you for polling')
          }
      })
    </script>
  </body>
</html>